version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/golang:1.11.10

    steps:
      - checkout
      - run:
          name: "Build Project Tarball"
          command: make
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_BRANCH} ./sample.tar.gz
