version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.10

    environment:
      ARTIFACT_PATH: /tmp/artifacts

    steps:
      - checkout
      - run: mkdir $ARTIFACT_PATH
      - run: make
      - run: mv sample.tar.gz $ARTIFACT_PATH/.
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} $ARTIFACT_PATH/

workflows:
  version: 2
  build:
    jobs:
    - build
