version: 2
jobs:
  build:
    docker:
      - image: cibuilds/github:0.10

    environment:
      ARTIFACT_PATH: /tmp/artifacts

    steps:
      - checkout
      - run: mkdir $ARTIFACT_PATH
      - run: make
      - run: mv sample.tar.gz $ARTIFACT_PATH/.
      - run:
        name: "Publish Release on GitHub"
        command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} $ARTIFACT_PATH/

workflows:
  version: 2
  build:
    jobs:
    - build
